import {
    Baby,
    Bus,
    Briefcase,
    Car,
    Coffee,
    CreditCard,
    Dumbbell,
    Film,
    Gamepad2,
    Gift,
    GraduationCap,
    Heart,
    Home,
    type LucideIcon,
    PawPrint,
    PiggyBank,
    Plane,
    ShoppingCart,
    Stethoscope,
    Utensils,
    Wallet,
} from "lucide-react"

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
    ShoppingCart,
    Home,
    Car,
    Utensils,
    Plane,
    Heart,
    Gift,
    Briefcase,
    GraduationCap,
    Gamepad2,
    Wallet,
    PiggyBank,
    CreditCard,
    Coffee,
    Bus,
    Film,
    Dumbbell,
    Stethoscope,
    Baby,
    PawPrint,
}

export const CATEGORY_ICON_NAMES = Object.keys(CATEGORY_ICONS)
